layout-parser: Fixing 'type' object is not subscriptable error
Fixing the below error due to incorrect object type usage

server/modules/main/models.py", line 30, in BoundingBox
    def from_xyxy(cls, coords: tuple[int, int, int, int]) -> 'BoundingBox':
TypeError: 'type' object is not subscriptable

Fixes: 8c922f4115fcb ("added option for dilation of words")
Signed-off-by: Devesh Sharma <sharma.98@iitj.ac.in>